spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

label:
  form:
    title: User Registration
    submit: Submit
    loginLink: Login
  user:
    firstName: First Name
    lastName: Last Name
    email: Email
    password: Password
    confirmPassword: Confirm Password